juniorUsca/get-things-done

- microservice/apiNode/.gitignore
- microservice/apiNode/README.md
- microservice/apiNode/index.js
- microservice/apiNode/package-lock.json
- microservice/apiNode/package.json
- microservice/apiNode/postman/Proyecto final.postman_collection.json
- microservice/apiNode/routes/inbox.js
- microservice/apiNode/routes/todo.js
Se realizo el crud de los inbox, basada en una propuesta de estrucutura de base de datos, usando una variable local.
> feat(apiNode): inbox CRUD and todo Read in a local variable

- .gitignore
Se agregaron las carpetas creadas por los ides de JetBrains en el  archivo gitignore para que no sean consideradas en los commits.
Resolve : #44
> feat(gitignore) : Se agregaron nuevas carpetas al archivo  gitignore

- microservice/apiNode/package-lock.json
- microservice/apiNode/routes/inbox.js
Se resolvió el bug encontrado en la ruta de listado de todos los inbox.
Fixes #50
> fix(microservicio de Inbox): Bug en la URL de listado general de inbox

- microservice/apiNode/package-lock.json
- microservice/apiNode/routes/inbox.js
Se resolvió el bug encontrado en la ruta de eliminación de un inbox específico.
Fix #55
> fix(microservicio de Inbox): Bug en la URL de eliminación de inbox

- microservice/apiNode/routes/inbox.js
Se corrigieron las falencias encontradas y mencionadas en el Issue #94 
**ID de usuario inexistente**
**ID de inbox inexistente**
Fix #94
> fix(microservicio de Inbox): Bug en la URL de edición de inbox

- MobileApp/Flutter/getthingsdone/README.md
Iré actualizando en cuanto encuentre errores y sus soluciones que les pueda ayudar.
> mejorar el readme.md de la aplicación de flutter #99

- microservice/apiNode/routes/inbox.js
Se corrigieron las falencias encontradas en la url de creación de inbox
Fix #103
> fix(microservicio de Inbox): Bug en la URL de creación de inbox

- app/src/pages/index.js
- app/src/pages/main.js
Uso de los calendarios de google para interfaz de tareas
> #issue56 feat(NextJs): Interfaz de calendario para NextJs

- microservice/api_Firebase/functions/src/routes/inbox.js
#133 Validaciones implementadas en cada ruta (get/post/delete/patch)
- Validacion cuando el usuario no existe
- Cambio de nombre en crear inbox, de inboz_id a inbox_id
- Validacion de la existencia de parametros necesarios en el body al enviar una solicitud
- Añadio tambien el campo status_done en cada ruta, esta muestra el estado de cada inbox (completo / incompleto)
> fix(inbox): validations when user is invalid

- MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
Reverts juniorUsca/get-things-done#116
Se tiene conflictos con el proyecto en Flutter
> CONFLICTOS CON EL PROYECTO FLUTTER

- MobileApp/Flutter/getthingsdone/pubspec.lock
- microservice/api_Firebase/functions/src/index.js
- microservice/api_Firebase/functions/src/routes/inbox.js
- microservice/api_Firebase/functions/src/routes/incubator.js
- microservice/api_Firebase/functions/src/routes/tickerfile.js
- microservice/api_Firebase/postman/Proyecto final Firebase.postman_collection.json
Se implemento el CRUD de las tareas de incubadora
Se tubo un percanse con el archivo pubspec.lock de MovileApp/Flutter, los cambios se realizaron de manera automatica por el IDE por lo que no se pudo controllar su modificacion con (git add .)
> feat(incubator): implement incubator CRUD'

- MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
- MobileApp/Flutter/getthingsdone/lib/Views/SigIn.dart
- MobileApp/Flutter/getthingsdone/lib/main.dart
Se creó la navegación el proyecto Flutter, esto se logró colocando en el archivo main.dart todas las rutas que estamos usando ahora. Y si se desea llamar desde otro archivo llamados al identificar de la ruta colocada en este main.
> #150 feat(Flutter): Se añadió la navegación en el proyecto Flutter

- MobileApp/Flutter/getthingsdone/android/app/build.gradle
- MobileApp/Flutter/getthingsdone/android/app/google-services.json
- MobileApp/Flutter/getthingsdone/android/app/src/main/AndroidManifest.xml
- MobileApp/Flutter/getthingsdone/android/build.gradle
- MobileApp/Flutter/getthingsdone/lib/Controllers/Controller.dart
- MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
- MobileApp/Flutter/getthingsdone/pubspec.lock
- MobileApp/Flutter/getthingsdone/pubspec.yaml
Se implemento el Login con Google con Firebase y se añadió un botón el cual es un botón de prueba que por ahora referencia a la pagina de singIn,
> #68 feat(flutter):Login con Google

- MobileApp/Flutter/getthingsdone/lib/Views/home_view/background.dart
- MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
- MobileApp/Flutter/getthingsdone/lib/Views/login_view/Login.dart
Se creo el diseño del homepage, la vista principal la cual los usuarios verán primero antes de loguearse.
> #69 feat(flutter): Diseño HomePage Fluter

- MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
- MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/background_lateral.dart
- MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/menu_lateral.dart
Se creo una barra lateral mediante la cual los usuarios podrán navegar entre las distintas vistas.
> #71 feat(flutter): Barra Latera

- MobileApp/Flutter/getthingsdone/lib/Views/calendar_view/calendario_page.dart
- MobileApp/Flutter/getthingsdone/lib/Views/calendar_view/event.dart
- MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/menu_lateral.dart
- MobileApp/Flutter/getthingsdone/pubspec.lock
- MobileApp/Flutter/getthingsdone/pubspec.yaml
Se añadió un calendario a nuestro aplicativo además se añadió un método el cual permite añadir eventos en nuestro calendario.
> #77 feat(flutter): Calendario y Anadir notas

- MobileApp/Flutter/getthingsdone/lib/Views/form_view/form_page.dart
- MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
- MobileApp/Flutter/getthingsdone/lib/Views/login_view/background_page.dart
Se diseño un formulario en el cual los usuarios puedan añadir una tarea, cabe aclarar que solo es diseño no es funcional.
> #70 feat(flutter): Diseño Formulario Nueva Tarea

- microservice/api_Firebase/functions/src/index.js
- microservice/api_Firebase/functions/src/routes/calendar.js
- microservice/api_Firebase/functions/src/routes/todo.js
- microservice/api_Firebase/functions/src/routes/utils.js
- microservice/api_Firebase/postman/Proyecto final Firebase.postman_collection.json
Se implemento el CRUD para las tareas que van en calendario en en microservicio de node con firebase
> feat(calendar-apinodefirebase): implement calendar CRUD

- microservice/api_Firebase/functions/src/index.js
- microservice/api_Firebase/functions/src/routes/calendar.js
- microservice/api_Firebase/functions/src/routes/inbox.js
- microservice/api_Firebase/functions/src/routes/incubator.js
- microservice/api_Firebase/functions/src/routes/tickerfile.js
- microservice/api_Firebase/functions/src/routes/todo.js
- microservice/api_Firebase/functions/src/routes/utils.js
- microservice/api_Firebase/postman/Proyecto final Firebase-Heroku.postman_collection.json
Se ha corregido unos percances presentados al desplegar el microservicio de Node con Firebase.
El microservicio ya esta disponible en [https://api-node-firebase.herokuapp.com/](https://api-node-firebase.herokuapp.com/)
Las consultas de Postman y mas detalles se encuentran en la issue #160
> fix(deploy-heroku): modified routes and fix inconsistent variables name

- microservice/apiNode/.babelrc
- microservice/apiNode/index.js
- microservice/apiNode/package-lock.json
- microservice/apiNode/package.json
- microservice/apiNode/tests/api.test.js
Se aplicaron los tests correspondientes a cada uno de los endpoints implementados en el microservicio Inbox, para ello se hizo uso de las herramientas Jest y Supertest.
Issue #13
> test(microservicio de Inbox): Aplicación de tests al microservicio Node-Inbox

- app/src/pages/404.js
- app/src/styles/globals.css
Se aplico un Diseño a la pagina de error 404, además de un botón de redirección hacia la pagina de logeo.
Se deberá cambiar al momento de tener una pagina de inicio.
> Diseño de la pagina de Error 404

- MobileApp/Flutter/getthingsdone/README.md
- MobileApp/Flutter/getthingsdone/lib/Views/login_view/Login.dart
- MobileApp/Flutter/getthingsdone/lib/bloc/login_bloc.dart
- MobileApp/Flutter/getthingsdone/lib/bloc/provider.dart
- MobileApp/Flutter/getthingsdone/lib/bloc/validators.dart
- MobileApp/Flutter/getthingsdone/lib/main.dart
Se crearon las validaciones de el Login.
> #173 feat(flutter): Validaciones para el LogIn

- MobileApp/Flutter/getthingsdone/lib/Views/login_view/SigIn.dart
Se realizaran las validaciones del Registro.
> #174 feat(flutter): Validacion de Registro

- MobileApp/Flutter/getthingsdone/README.md
Se añadió información en el Redme para poder usar el Login con Google.
> #172 feat(flutter): Informacion para el Login con Google

- app/src/pages/welcome.js
Se implemento un Diseño de la pagina de Bienvenida, con algunas primeras opciones, todavía no funcionales.
La pagina todavía no esta enlazada con el logeo.
> Diseño de la pagina de Bienvenida

- app/src/components/calendar/CalendarComponent.js
- app/src/components/calendar/CalendarEvent.js
> feat(app-nextJS):Implementacion de componente CalendarEvent para Calendario

- documentation/gtd.sql
- microservice/apiJava/pom.xml
- microservice/apiJava/src/main/resources/application.properties
- microservice/apiJava/src/main/resources/static/index.html
Se creo el  script para la base de datos postgresql de acuerdo a los modelos propuestos
> [FIX] Script de la base de datos gtd #132

- documentation/credenciales_aws_rds.md
- microservice/apiJava/README.md
- microservice/apiJava/pom.xml
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/ICalendar.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IInbox.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IIncubadura.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/INextActions.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/ITicklerFile.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IUsers.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Calendar.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Inbox.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Incubadura.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/NextActions.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/TicklerFile.java
- microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Users.java
- microservice/apiJava/src/main/resources/application.properties
Se creo el archivo credenciales_aws_rds.md con las credenciales para acceder publicamente a la bd gtd
> [FIX] CREDENCIALES DEL SERVICIO RDS EN AWS #194

- app/package-lock.json
- app/package.json
- app/postcss.config.js
- app/src/components/Layout/Navbar/Navbar.js
- app/src/components/Layout/Sidebar/Sidebar.js
- app/src/components/Layout/layout.js
- app/src/pages/calendar.js
- app/src/pages/inbox.js
- app/src/styles/globals.css
- app/tailwind.config.js
Se creo la interfaz para el Dashboard usando la libreria Tailwindcss.
> issue#193 feat(Creacion de la interfaz del Dashboard - menus)

- app/src/pages/inbox.js
Descuidadamente, los cambios para este pull request se subieron en el anterior que hice. Este pull request busca mostrar que estos cambios pertenecen al issue #207. Solo se trata de un archivo afortunadamente, así es sencillo de reconocer a simple vista. Igualmente se han agregado pocos comentarios para señalar las inclusiones.
> Reconociendo cambios de edición y actualización de tareas

- app/package-lock.json
- app/package.json
- app/src/pages/SnapBar.js
- app/src/pages/welcome.js
Se integrara un menú lateral que mostrara opciones de navegación para el aplicativo web (NextJS).
Además de la implementación de una nueva dependencia la cual permitirá controlar las transiciones entre lo que viene a ser el tamaño de pantalla y la adaptación de los items y de igual manera de la transición de pantalla chica a pantalla grande de los items.
> Implementacion de Menu Adaptativo NextJS

- MobileApp/Flutter/getthingsdone/lib/Controllers/todo_controller.dart
- MobileApp/Flutter/getthingsdone/lib/Models/todo.dart
- MobileApp/Flutter/getthingsdone/lib/Views/todo_view/home_screen.dart
- MobileApp/Flutter/getthingsdone/lib/repository/repository.dart
- MobileApp/Flutter/getthingsdone/lib/repository/todo_repository.dart
- MobileApp/Flutter/getthingsdone/pubspec.lock
- MobileApp/Flutter/getthingsdone/pubspec.yaml
se agrego la dependencia http y se uso una apirest
> Se agrego consumo de http get

- MicroserviceImbox/ApiNodeJS/src/components/imbox/application/CreateImbox.js
- MicroserviceImbox/ApiNodeJS/src/components/imbox/application/UpdateImbox.js
se modifico la estructura de la tabla imbox ya que esta necesita ser referenciada con un id_usuario para que solo se listen los imbox de un usuario
> fix(MicroserviceImbox): modificando la estructura de la tabla IMBOX

- app/src/pages/SnapBar.js
Se implemento lo que viene a ser la funcionalidad de Ruteo al SnapBar anteriormente implementado, además de arreglar y mejorar algunos aspectos
> Implementacion Funcionalidad al Snap Bar vista Welcome NextJS

- MicroserviceImbox/microservice_calendary/.env.example
- MicroserviceImbox/microservice_calendary/.eslintrc.cjs
- MicroserviceImbox/microservice_calendary/package-lock.json
- MicroserviceImbox/microservice_calendary/package.json
- MicroserviceImbox/microservice_calendary/src/components/calendary/application/CreateCalendary.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/application/DeleteCalendary.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/application/GetCalendary.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/application/ShowAllCalendary.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/application/UpdateCalendary.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/controller.js
- MicroserviceImbox/microservice_calendary/src/components/calendary/infraestructure/MongoCalendaryRepository.js
- MicroserviceImbox/microservice_calendary/src/config.js
- MicroserviceImbox/microservice_calendary/src/index.js
- MicroserviceImbox/microservice_calendary/src/lib/mongo.js
- MicroserviceImbox/microservice_calendary/src/routes/calendary.js
- MicroserviceImbox/microservice_calendary/src/utils/middlewares/errorHandlers.js
- MicroserviceImbox/microservice_calendary/src/utils/middlewares/notFoundHandler.js
Se implemento el microservicio de la tabla Calendario con las funcionalidades indicadas en el issue #108  , el microservicio cuenta con una estructura DDD y conexión una base de datos mongo.
> feat(MicroservicioCalendary): Implementacion del microservice con DDD

- MicroserviceImbox/microservice_calendary/src/routes/calendary.js
- MicroserviceImbox/microservice_tickler_file/.env.example
- MicroserviceImbox/microservice_tickler_file/.eslintrc.cjs
- MicroserviceImbox/microservice_tickler_file/package-lock.json
- MicroserviceImbox/microservice_tickler_file/package.json
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/CreateCalendary.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/DeleteCalendary.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/GetCalendary.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/ShowAllCalendary.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/UpdateCalendary.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/controller.js
- MicroserviceImbox/microservice_tickler_file/src/components/calendary/infraestructure/MongoCalendaryRepository.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/application/CreateTickler.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/application/DeleteTickler.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/application/GetTickler.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/application/ShowAllTickler.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/application/UpdateTickler.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/controller.js
- MicroserviceImbox/microservice_tickler_file/src/components/ticklerFile/infraestructure/MongoTicklerRepository.js
- MicroserviceImbox/microservice_tickler_file/src/config.js
- MicroserviceImbox/microservice_tickler_file/src/index.js
- MicroserviceImbox/microservice_tickler_file/src/lib/mongo.js
- MicroserviceImbox/microservice_tickler_file/src/routes/ticklerfile.js
- MicroserviceImbox/microservice_tickler_file/src/utils/middlewares/errorHandlers.js
- MicroserviceImbox/microservice_tickler_file/src/utils/middlewares/notFoundHandler.js
Se implemento el microservicio de la tabla Tickler File con las funcionalidades indicadas en el issue #107 , el microservicio cuenta con una estructura DDD y conexión una base de datos mongo.
> feat(MicroserviceTiclerFile): Implementacion microservicio con DDD

- app/src/pages/anotation.js
Un diseño tipo Card de una nueva anotación, también podrá generar notas de voz.
> Diseño de Card Anotation

- app/src/pages/404.js
- app/src/styles/globals.css
> Page 404 Modification

- README.md
> Adding deployment link to README
